"""
This type stub file was generated by pyright.
"""

from ..._utils import deprecated

__all__ = ["log2_int", "bits_for", "value_bits_sign"]

@deprecated("instead of `log2_int`, use `amar")
def log2_int(n, need_pow2=...): ...
@deprecated("instead of `bits_for`, use `amar")
def bits_for(n, require_sign_bit=...): ...
@deprecated("instead of `value_bits_sign(v)`,")
def value_bits_sign(v): ...
