"""
This type stub file was generated by pyright.
"""

from ...hdl.ast import *
from ...hdl.xfrm import (
    DomainRenamer as NativeDomainRenamer,
    EnableInserter as NativeEnableInserter,
    ResetInserter as NativeResetInserter,
)
from ..._utils import deprecated

__all__ = ["ResetInserter", "CEInserter", "ClockDomainsRenamer"]

class _CompatControlInserter:
    _control_name = ...
    _native_inserter = ...
    def __init__(self, clock_domains=...) -> None: ...
    def __call__(self, module): ...

@deprecated(
    "instead of `migen.fhdl.decorator"
    "use `amaranth.hdl.xfrm.ResetInse"
    "a dict of reset signals (or a si"
    "a set of clock domain names (or "
)
class CompatResetInserter(_CompatControlInserter):
    _control_name = ...
    _native_inserter = NativeResetInserter

@deprecated(
    "instead of `migen.fhdl.decorator"
    "use `amaranth.hdl.xfrm.EnableIns"
    "a dict of enable signals (or a s"
    "a set of clock domain names (or "
)
class CompatCEInserter(_CompatControlInserter):
    _control_name = ...
    _native_inserter = NativeEnableInserter

class CompatClockDomainsRenamer(NativeDomainRenamer):
    def __init__(self, cd_remapping) -> None: ...

ResetInserter = CompatResetInserter
CEInserter = CompatCEInserter
ClockDomainsRenamer = CompatClockDomainsRenamer
