"""
This type stub file was generated by pyright.
"""

from ..._utils import deprecated, extend
from ...hdl.ast import *
from ...hdl.ir import Elaboratable
from ...hdl.mem import Memory as NativeMemory
from .module import Module as CompatModule

__all__ = ["TSTriple", "Instance", "Memory", "READ_FIRST", "WRITE_FIRST", "NO_CHANGE"]

class TSTriple:
    def __init__(self, bits_sign=..., min=..., max=..., reset_o=..., reset_oe=..., reset_i=..., name=...) -> None: ...
    def __len__(self): ...
    def get_tristate(self, io): ...

class Tristate(Elaboratable):
    def __init__(self, target, o, oe, i=...) -> None: ...
    def elaborate(self, platform): ...

class _MemoryPort(CompatModule):
    def __init__(
        self, adr, dat_r, we=..., dat_w=..., async_read=..., re=..., we_granularity=..., mode=..., clock_domain=...
    ) -> None: ...

@extend(NativeMemory)
@deprecated("it is not necessary or permitted")
def elaborate(self, platform): ...

class CompatMemory(NativeMemory, Elaboratable):
    def __init__(self, width, depth, init=..., name=...) -> None: ...
    @deprecated("instead of `get_port()`, use `re")
    def get_port(
        self, write_capable=..., async_read=..., has_re=..., we_granularity=..., mode=..., clock_domain=...
    ): ...

Memory = CompatMemory
