repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: double-quote-string-fixer
  - id: mixed-line-ending
  - id: check-docstring-first
  - id: check-json
  - id: check-yaml
  - id: check-xml
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.7
  hooks:
  - id: autopep8

- repo: meta
  hooks:
  - id: check-useless-excludes
