
[project]
name = "coreblocks"
dynamic = ["version"]
description = "Coreblocks is an experimental, modular out-of-order RISC-V core generator implemented in Amaranth"
license = {file = "LICENSE"}

requires-python = ">=3.11"

dependencies = [
    "amaranth[builtin-yosys]>=0.5.4",
    "amaranth-stubs>=0.1.1",
    "dataclasses-json>=0.6.3",
    "transactron @ git+https://github.com/kuznia-rdzeni/transactron.git@343500bb1971de64b0864198478420c4b68e5e8e",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[dependency-groups]
dev = [
    "black>=24.4.2",
    "docutils>=0.15.2",
    "flake8>=7.0.0",
    "pep8-naming>=0.13.3",
    "markupsafe>=2.0.1",
    "myst-parser>=0.18.0",
    "numpydoc>=1.5.0",
    "parameterized>=0.8.1",
    "pre-commit>=2.16.0",
    "pyright>=1.1.393",
    "Sphinx>=5.1.1",
    "sphinx-rtd-theme>=1.0.0",
    "sphinxcontrib-mermaid>=0.8.1",
    "cocotb>=1.8.1",
    "cocotb-bus>=0.2.1",
    "pytest>=8.0.0",
    "pytest-xdist>=3.5.0",
    "pyelftools>=0.29",
    "tabulate>=0.9.0",
    "filelock>=3.13.1",
    "hypothesis>=6.99.6",
    "yowasp-runtime",
    "yowasp-yosys>=0.55.0.3.post946.dev0",
    "yowasp-nextpnr-ecp5>=0.7",
]


[tool.pyright]
include = [
    "coreblocks",
    "test",
    "constants",
    "scripts"
  ]

exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/external"
  ]

reportMissingImports = true
reportMissingTypeStubs = false
reportWildcardImportFromLibrary = false

[tool.pytest.ini_options]
minversion = "7.2.2"
testpaths = "tests"
norecursedirs = ['*.egg', '.*', 'build', 'dist', 'venv', '__traces__', '__pycache__', 'test/external']
filterwarnings = [
    "ignore:cannot collect test class 'TestbenchContext':pytest.PytestCollectionWarning",
    "ignore:cannot collect test class 'TestbenchIO':pytest.PytestCollectionWarning",
    "ignore:No files were found in testpaths:pytest.PytestConfigWarning:",
    ]

[tool.pdm.scripts._.env]
YOSYS = "yowasp-yosys"
NEXTPNR_ECP5 = "yowasp-nextpnr-ecp5"
ECPPACK = "yowasp-ecppack"
[tool.pdm.scripts]
synthesize = "scripts/synthesize.py"
