"""
This type stub file was generated by pyright.
"""

from .._utils import deprecated
from ..hdl.cd import *
from ..hdl.ir import *

__all__ = ["Settle", "Delay", "Tick", "Passive", "Active", "Simulator"]
class Command:
    ...


class Settle(Command):
    def __repr__(self): # -> Literal['(settle)']:
        ...
    


class Delay(Command):
    def __init__(self, interval=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class Tick(Command):
    def __init__(self, domain=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class Passive(Command):
    def __repr__(self): # -> Literal['(passive)']:
        ...
    


class Active(Command):
    def __repr__(self): # -> Literal['(active)']:
        ...
    


class Simulator:
    def __init__(self, fragment, *, engine=...) -> None:
        ...
    
    def add_process(self, process): # -> None:
        ...
    
    def add_sync_process(self, process, *, domain=...): # -> None:
        ...
    
    def add_clock(self, period, *, phase=..., domain=..., if_exists=...):
        """Add a clock process.

        Ad"""
        ...
    
    def reset(self): # -> None:
        """Reset the simulation.

        A"""
        ...
    
    @deprecated("instead of `sim.step()`, use `si")
    def step(self): # -> bool:
        ...
    
    def advance(self): # -> bool:
        """Advance the simulation.

       """
        ...
    
    def run(self): # -> None:
        """Run the simulation while any pro"""
        ...
    
    def run_until(self, deadline, *, run_passive=...): # -> None:
        """Run the simulation until it adva"""
        ...
    
    def write_vcd(self, vcd_file, gtkw_file=..., *, traces=...): # -> _GeneratorContextManager[None]:
        """Write waveforms to a Value Chang"""
        ...
    


