"""
This type stub file was generated by pyright.
"""

from ._base import BaseProcess

__all__ = ["PyClockProcess"]

class PyClockProcess(BaseProcess):
    def __init__(self, state, signal, *, phase, period) -> None: ...
    def reset(self): ...
    def run(self): ...
