"""
This type stub file was generated by pyright.
"""

from .._toolchain.yosys import *

__all__ = ["YosysError", "convert", "convert_fragment"]

def convert_fragment(*args, black_boxes=..., **kwargs): ...
def convert(*args, black_boxes=..., **kwargs): ...
