"""
This type stub file was generated by pyright.
"""

__all__ = ["log2_int", "bits_for"]
def log2_int(n:int, need_pow2:bool=...) -> int:
    ...

def bits_for(n:int, require_sign_bit:bool=...) -> int:
    ...

