"""
This type stub file was generated by pyright.
"""

__all__ = ["log2_int", "bits_for"]
def log2_int(n, need_pow2=...): # -> Literal[0]:
    ...

def bits_for(n, require_sign_bit=...): # -> Literal[1, 0]:
    ...

