"""
This type stub file was generated by pyright.
"""

from .. import *

__all__ = ["FFSynchronizer", "AsyncFFSynchronizer", "ResetSynchronizer", "PulseSynchronizer"]

class FFSynchronizer(Elaboratable):
    """Resynchronise a signal to a diff"""

    def __init__(self, i, o, *, o_domain=..., reset=..., reset_less=..., stages=..., max_input_delay=...) -> None: ...
    def elaborate(self, platform): ...

class AsyncFFSynchronizer(Elaboratable):
    """Synchronize deassertion of an as"""

    def __init__(self, i, o, *, o_domain=..., stages=..., async_edge=..., max_input_delay=...) -> None: ...
    def elaborate(self, platform): ...

class ResetSynchronizer(Elaboratable):
    """Synchronize deassertion of a clo"""

    def __init__(self, arst, *, domain=..., stages=..., max_input_delay=...) -> None: ...
    def elaborate(self, platform): ...

class PulseSynchronizer(Elaboratable):
    """A one-clock pulse on the input p"""

    def __init__(self, i_domain, o_domain, *, stages=...) -> None: ...
    def elaborate(self, platform): ...
