"""
This type stub file was generated by pyright.
"""

from .. import *
from ..hdl.rec import *

__all__ = ["pin_layout", "Pin"]

def pin_layout(width, dir, xdr=...):
    """
    Layout of the platform inte"""
    ...

class Pin(Record):
    """
    An interface to an I/O buff"""

    def __init__(self, width, dir, *, xdr=..., name=..., src_loc_at=...) -> None: ...
