"""
This type stub file was generated by pyright.
"""

from .ast import *

__all__ = ["Direction", "DIR_NONE", "DIR_FANOUT", "DIR_FANIN", "Layout", "Record"]
Direction = ...
DIR_NONE = ...
DIR_FANOUT = ...
DIR_FANIN = ...
class Layout:
    @staticmethod
    def cast(obj, *, src_loc_at=...): # -> Layout:
        ...
    
    def __init__(self, fields, *, src_loc_at=...) -> None:
        ...
    
    def __getitem__(self, item): # -> Layout:
        ...
    
    def __iter__(self): # -> Generator[tuple[Unknown, Unknown, Unknown], None, None]:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class Record(ValueCastable):
    @staticmethod
    def like(other, *, name=..., name_suffix=..., src_loc_at=...): # -> Record:
        ...
    
    def __init__(self, layout, *, name=..., fields=..., src_loc_at=...) -> None:
        ...
    
    def __getattr__(self, name):
        ...
    
    def __getitem__(self, item):
        ...
    
    @ValueCastable.lowermethod
    def as_value(self): # -> Cat:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def shape(self): # -> Shape:
        ...
    
    def connect(self, *subordinates, include=..., exclude=...):
        ...
    


