#!/usr/bin/env python3

import pathlib
import sys
from argparse import ArgumentParser, FileType

par = ArgumentParser()
par.add_argument('-p', '--prune', action='store_true', help='ignore disconnected nodes')
par.add_argument('-f', '--format', default='elk', nargs='?')
par.add_argument('ofile', type=FileType('w'))

arg = par.parse_args()

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

from coreblocks.params.genparams import GenParams
from coreblocks.transactions.graph import TracingFragment
from test.test_core import TestElaboratable
from coreblocks.fu.alu import ALUComponent
from coreblocks.fu.jumpbranch import JumpComponent
from coreblocks.lsu.dummyLsu import LSUBlockComponent
from coreblocks.stages.rs_func_block import RSBlockComponent

gp = GenParams("rv32i", [RSBlockComponent([ALUComponent(), JumpComponent()], rs_entries=4), LSUBlockComponent()])
elaboratable = TestElaboratable(gp)
fragment = TracingFragment.get(elaboratable, platform=None).prepare()

core = fragment
while not hasattr(core, "transactionManager"):
    core = core._tracing_original

mgr = core.transactionManager

with arg.ofile as fp:
    graph = mgr.visual_graph(fragment)
    if arg.prune:
        graph.prune()
    graph.dump(fp, arg.format)
