#!/usr/bin/env python3

import pathlib
import sys
from argparse import ArgumentParser, FileType
from amaranth.hdl.ir import Fragment

par = ArgumentParser()
par.add_argument('ofile', type=FileType('w'))

arg = par.parse_args()

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

from coreblocks.genparams import GenParams
from test.test_core import TestElaboratable

gp = GenParams("rv32i", phys_regs_bits=6, rob_entries_bits=7)
elaboratable = TestElaboratable(gp)
elaboratable._MustUse__used = True
transactionModule = elaboratable.elaborate(None)
frag = Fragment.get(transactionModule, platform=None).prepare()

mgr = transactionModule.transactionManager

with arg.ofile as fp:
    mgr.dump_visual_graph(fp, elaboratable)
