name: Deploy Wiki

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/deploy_wiki.yml'
    branches:
      - master

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push Wiki Changes
        run: .ci/push_docs.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.OWNER_MAIL }}
          GH_NAME: ${{ github.repository_owner }}