name: CI

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master
      - 'feature/**'
  workflow_dispatch:

jobs:
  build-core:
    name: Synthesize full core
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install Coreblocks dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install .

      - name: Generate Verilog
        run: |
          . venv/bin/activate
          PYTHONHASHSEED=0 TRANSACTRON_VERBOSE=1 python3 -m coreblocks.gen_verilog --verbose --config full

      - uses: actions/upload-artifact@v7
        with:
          name: "verilog-full-core"
          path: |
            core.v
            core.v.json

  build-regression-tests:
    name: Build regression tests (riscv-tests)
    runs-on: ubuntu-latest
    container: ghcr.io/kuznia-rdzeni/riscv-toolchain:2024.12.07
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get submodules HEAD hash
        run: |
          git config --global --add safe.directory /__w/coreblocks/coreblocks
          git submodule > .gitmodules-hash

      - name: Cache regression-tests
        id: cache-regression
        uses: actions/cache@v4
        env:
          cache-name: cache-regression-tests
        with:
          path: test/external/riscv-tests/test-*
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles(
              '**/test/external/riscv-tests/environment/custom/**',
              '**/test/external/riscv-tests/Makefile',
              '**/.gitmodules-hash',
              '**/docker/riscv-toolchain.Dockerfile',
              '**/.github/workflows/main.yml'
            ) }}
          lookup-only: true

      - if: ${{ steps.cache-regression.outputs.cache-hit != 'true' }}
        name: Checkout with submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - if: ${{ steps.cache-regression.outputs.cache-hit != 'true' }}
        run: cd test/external/riscv-tests && make

      - if: ${{ steps.cache-regression.outputs.cache-hit != 'true' }}
        name: Upload riscv-tests
        uses: actions/upload-artifact@v7
        with:
          path: test/external/riscv-tests

  run-regression-tests:
    name: Run regression tests (riscv-tests)
    runs-on: ubuntu-22.04  # older version for compatibility with Docker image
    timeout-minutes: 45
    container: ghcr.io/kuznia-rdzeni/verilator:v5.008-2023.11.19_v
    needs: [ build-regression-tests, build-core ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get submodules HEAD hash
        run: |
          git config --global --add safe.directory /__w/coreblocks/coreblocks
          git submodule > .gitmodules-hash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[dev]"

      - uses: actions/download-artifact@v8
        name: Download full verilog core
        with:
          name: "verilog-full-core"
          path: .

      - uses: actions/cache@v4
        name: Download tests from cache
        env:
          cache-name: cache-regression-tests
        with:
          path: test/external/riscv-tests/test-*
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles(
              '**/test/external/riscv-tests/environment/custom/**',
              '**/test/external/riscv-tests/Makefile',
              '**/.gitmodules-hash',
              '**/docker/riscv-toolchain.Dockerfile',
              '**/.github/workflows/main.yml'
            ) }}
          fail-on-cache-miss: true

      - name: Run tests
        run: |
          . venv/bin/activate
          scripts/run_tests.py -a regression -v

      - name: Check regression with pysim
        run: |
          . venv/bin/activate
          ./scripts/run_tests.py -c 1 -a -b pysim regression

  build-arch-regression-tests:
    name: Build arch regression tests (riscv-arch-test)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/riscv/act4-build:sha-b16f90769d554d9dd42fa71fe9ba64054a4b7964
      options: --user root
    timeout-minutes: 20
    steps:
      - name: Add required tools for github CI
        run: |
          apt-get update
          apt-get install -y git tar gzip curl ca-certificates build-essential libgmp-dev

      - name: Checkout
        uses: actions/checkout@v6

      - name: Get submodules HEAD hash
        working-directory: .
        run: |
          git config --global --add safe.directory /__w/coreblocks/coreblocks
          git submodule > .gitmodules-hash

      - name: Cache arch regression tests
        id: cache-arch-regression-tests
        uses: actions/cache@v4
        env:
          cache-name: cache-arch-regression-tests
        with:
          path: |
            test/external/riscv-arch-test/elfs/**/*.elf
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles(
              '**/test/external/riscv-arch-test/Makefile',
              '**/test/external/riscv-arch-test/coreblocks/**',
              '**/.gitmodules-hash',
              '**/.github/workflows/main.yml'
            ) }}

      - if: ${{ steps.cache-arch-regression-tests.outputs.cache-hit != 'true' }}
        name: Checkout with submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - if: ${{ steps.cache-arch-regression-tests.outputs.cache-hit != 'true' }}
        name: Trust riscv-arch-test with mise
        run: mise trust test/external/riscv-arch-test/.mise.toml

      - if: ${{ steps.cache-arch-regression-tests.outputs.cache-hit != 'true' }}
        name: Build arch regression tests
        run: make -C test/external/riscv-arch-test -j $(nproc)

      - name: Upload riscv-arch-test tests
        uses: actions/upload-artifact@v7
        with:
          name: "riscv-arch-test-elfs"
          path: test/external/riscv-arch-test/elfs

  run-arch-regression-tests:
    strategy:
      fail-fast: false
      matrix:
        config: [cocotb, pysim]
    name: Run arch regression tests (riscv-arch-test)
    runs-on: ubuntu-22.04  # older version for compatibility with Docker image
    container: ghcr.io/kuznia-rdzeni/verilator:v5.008-2023.11.19_v
    timeout-minutes: 180
    needs: [ build-arch-regression-tests ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get submodules HEAD hash
        working-directory: .
        run: |
          git config --global --add safe.directory /__w/coreblocks/coreblocks
          git submodule > .gitmodules-hash

      - name: Restore arch regression tests cache
        uses: actions/cache@v4
        env:
          cache-name: cache-arch-regression-tests
        with:
          path: |
            test/external/riscv-arch-test/elfs/**/*.elf
          key: ${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles(
              '**/test/external/riscv-arch-test/Makefile',
              '**/test/external/riscv-arch-test/coreblocks/**',
              '**/.gitmodules-hash',
              '**/.github/workflows/main.yml'
            ) }}
          fail-on-cache-miss: true
          lookup-only: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[dev]"

      - name: Run arch regression tests
        run: |
          . venv/bin/activate
          if [ "${{ matrix.config }}" = "cocotb" ]; then
            ./scripts/run_tests.py --arch-tests -v -b cocotb regression
          else
            ./scripts/run_tests.py --arch-tests -v -b pysim -c 1 -j 0 'regression.*not'
          fi

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 150
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install ".[dev]"
          sudo apt-get install -y binutils-riscv64-unknown-elf

      - name: Run tests
        run: ./scripts/run_tests.py -v

      - name: Check traces and profiles
        run: ./scripts/run_tests.py -t -p -c 1 TestCore

      - name: Check listing tests
        run: ./scripts/run_tests.py -l

  lint:
    name: Check code formatting and typing
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install ".[dev]"

      - name: Check format
        run: ./scripts/lint.sh check_format

      - name: Check types
        run: ./scripts/lint.sh check_types

      - name: Check line endings
        run: |
          git add --renormalize .
          git diff --cached --exit-code

      - name: Check pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
