name: Test results

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
permissions: {}

jobs:
  make-test-report:
    name: Make test report
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    permissions:
      checks: write
      actions: read

    steps:
      - name: Download and extract artifacts
         uses: dawidd6/action-download-artifact@v2
         with:
            run_id: ${{ github.event.workflow_run.id }}
            path: artifacts

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: cocotb test results
          comment_mode: off
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/regression_tests_artifacts/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: artifacts/regression_tests_artifacts/test/regression/cocotb/results.xml
